services:
  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER - e $$POSTGRES_PASSWORD=password -h $$(hostname -i)"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:8000"
    env_file: node-video-crime-miner/.env